# -*- coding: utf-8 -*-
"""28p.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iG6RF8OaxJL8n5sg3g47UUWp9B8UAV1h
"""

def stringadd(str1):
  length = len(str1)

  if length > 2:
    if str1[-3:] == 'ing':
      str1 += 'ly'
    else:
      str1 += 'ing'

  return str1
print(stringadd('Enjoy'))
print(stringadd('Play'))
print(stringadd('willing'))