# -*- coding: utf-8 -*-
"""29p.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VB4RhbtcSUhndUPv7IXRKRkv-aCQdIKQ
"""

def getmax(b):
    return len(max(b,key=len))
a=[]
n= int(input("Enter the number of elements in list:"))
for x in range(0,n):
    e=input("Enter Element : ")
    a.append(e)
print("The length of longest word is :", getmax(a))